# Generated by Django 4.1.7 on 2023-03-09 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_tittle', models.CharField(max_length=100)),
                ('blog_description', models.TextField(max_length=350)),
                ('created_date', models.DateTimeField()),
                ('blog_image', models.ImageField(upload_to='')),
                ('blog_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
